// Generated by CoffeeScript 1.10.0
'use strict';

/**
 * @ngdoc function
 * @name sgaAdminApp.controller:LayoutCtrl
 * @description
 * # LayoutCtrl
 * Controller of the sgaAdminApp
 */
angular.module('sgaAdminApp')
	.controller('LayoutCtrl', [
		'$scope', 
		'$location', 
		function($scope, $location) {}]);
