// Generated by CoffeeScript 1.10.0
'use strict';

/**
 * @ngdoc function
 * @name sgaAdminApp.controller:LoginCtrl
 * @description
 * # LoginCtrl
 * Controller of the sgaAdminApp
 */
angular.module('sgaAdminApp').controller('LoginCtrl', [
	'$scope', '$location', 'permissionService', 'ipCookie', 'config', 'modalManager', 'Auth', 'User', 'UsersApi',
	function($scope, $location, permissionService, ipCookie, config, modalManager, Auth, User, UsersApi) {
		$scope.loginFail = false;
		$scope.user = {
			Name: '',
			Password: '',
			SourceToken: 'SUGAR'
    };
    Auth.set(config.tokens.apiVersion, config.api.version);
		$scope.permissionService = permissionService;

		$scope.login = function() {
			return User.login($scope.user).then(function(res) {
				var ref, returnPath;
				if (res.status === 200 && res.data != null) {
          $scope.loggedIn(res.data);
				}
			}).catch(function(res) {
					$scope.loginFail = true;
					var name = false;
			});
    };

    $scope.register = function() {
      return User.register($scope.user).then(function(res){
        if (res.status === 200 && res.data != null) {
          $scope.loggedIn(res.data);
        }
      }).catch(function(res){
        $scope.loginFail = true;
        var name = false;
      });
    };

    $scope.loggedIn = function(data) {
      var claims = [];
      var id = data['response']['user'].id;

      ipCookie("userId", id);
      var roleRequest = {};

      $scope.permissionService.get(id).then(function() {
        return $location.path('/');
      });
    };
	}
]);
