// Generated by CoffeeScript 1.10.0
'use strict';

/**
 * @ngdoc function
 * @name sgaAdminApp.controller:LoginCtrl
 * @description
 * # LoginCtrl
 * Controller of the sgaAdminApp
 */
angular.module('sgaAdminApp').controller('LoginCtrl', [
	'$scope', '$location', 'permissionService', 'ipCookie', 'config', 'modalManager', 'Auth', 'User', 'UsersApi',
	function($scope, $location, permissionService, ipCookie, config, modalManager, Auth, User, UsersApi) {
		$scope.loginFail = false;
		$scope.user = {
			Name: '',
			Password: '',
			SourceToken: 'SUGAR'
    };
    Auth.set(config.tokens.apiVersion, config.api.version);
		$scope.permissionService = permissionService;

		return $scope.login = function() {

			return User.login($scope.user).then(function(res) {
				var ref, returnPath;
				if (res.status === 200 && res.data != null) {

					var claims = [];
					var id = res.data['response']['user'].id;

					ipCookie("userId", id);
					$scope.permissionService.get(id).then(function() {

						// returnPath = $location.search()["return"];
						// if (returnPath != null) {
						// 	$location.search('return', null);
						// 	return $location.path(returnPath);
						// } else {
						 	return $location.path('/');
						// }
					});
					//TODO dont let players with no permissions login - error
				}
			}).catch(function(res) {
				if (res.status === -1) {
					$scope.loginFail = true;
					var name = false;
				}

			});;
		};
	}
]);
