// Generated by CoffeeScript 1.10.0
'use strict';

/**
  * @ngdoc function
  * @name sgaAdminApp.controller:MainCtrl
  * @description
  * # MainCtrl
  * Controller of the sgaAdminApp
 */
angular.module('sgaAdminApp').controller('MainCtrl', ['config', 'Auth', function(config, Auth) {
  Auth.set(config.tokens.apiVersion, config.api.version);
}]);
