// Generated by CoffeeScript 1.10.0
'use strict';

/**
 * @ngdoc function
 * @name sgaAdminApp.controller:showAchievementsCtrl
 * @description
 * # showAchievementsCtrl
 * Controller of the sgaAdminApp
 */
angular.module('sgaAdminApp').controller('AchievementShowCtrl', [
	'$scope', '$routeParams', '$location', 'modalManager', 'AchievementsApi',
	function($scope, $routeParams, $location, modalManager, AchievementsApi) {
		$scope.itemtype = $routeParams.itemtype;
		$scope.itemId = $routeParams.itemId;

		$scope.items = [];
		$scope.criterias = 1;

		$scope.gameName = '';
		$scope.gameFound = true;

		$scope.pagination = {
			perPage: 10,
			currentPage: 1
		};
		$scope.init = function() {
			if ($scope.itemId != "global")
			{
				AchievementsApi['achievements'].list($scope.itemId).then(function(res) {
					if (res.status === 200 && res.data != null) {
						$scope.items = res.data['response'];
						$scope.range();
					}
				});
				AchievementsApi['games'].get($scope.itemId).then(function(res) {
				if (res.status === 200 && res.data != null) {
					$scope.gameName = res.data['response'].name;
				} else {
					$scope.gameFound = false;
				}
				}).catch(function() {
					$scope.gameFound = false;
				});
			}
			else
			{
				AchievementsApi['achievements'].global().then(function(res){
					if (res.status === 200 && res.data != null) {
						$scope.items = res.data['response'];
						$scope.range();
					}
				});
				$scope.gameName = "Global";
				$scope.gameFound = true;
			}
			
		};
		$scope.range = function(min, max, step) {
			if ($scope.items == null)
				return 0;
			step = step || 1;
			min = 0;
			max = $scope.items.length - 1;
			var input = [];
			for (var i = min; i <= max; i += step) {
				input.push(i);
			}
			return input;
		};
		$scope.criteriaRange = function(index) {
			if ($scope.items == null)
				return 0;
			var step = 1;
			var min = 1;
			var max = $scope.items[index].evaluationCriterias.length;
			var input = [];
			for (var i = min; i <= max; i += step) {
				input.push(i);
			}
			return input;
		};
		$scope.remove = function(item) {
			return modalManager.open('deleteAchievement', {
				item: item,
				itemId: $scope.itemId
			});
		};
		$scope.add = function(item) {
			$location.path('/achievements/' + $scope.itemId + '/new');
		};
		$scope.back = function() {
			//go back to achievements game list
			$location.path("/achievements");
		};
		return $scope.$on('savedItem', function(event, args) {
			return $scope.init();
		});
	}
]).controller('ConfirmDeleteAchievementModalCtrl', [
	'$scope', '$rootScope', '$uibModalInstance', 'AchievementsApi', 'modaldata',
	function($scope, $rootScope, $uibModalInstance, AchievementsApi, modaldata) {

		$scope.item = modaldata.item;
		$scope.itemId = modaldata.itemId;

		if (modaldata.item != null) {
			$scope.item = modaldata.item;
		} else if (modaldata.itemid != null) {
			$scope.item = {};
			usersApi[$scope.itemtype].get(modaldata.itemid).then(function(data) {
				return console.log(data);
			});
		}
		$scope["delete"] = function() {
			if ($scope.itemId != "global")
			{
				AchievementsApi['achievements'].delete(item.token, $scope.itemId).then(function(res) {
					$uibModalInstance.close();
					return $rootScope.$broadcast('savedItem');
				});
			}
			else
			{
				AchievementsApi['achievements'].deleteGlobal(item.token).then(function(res) {
					$uibModalInstance.close();
					return $rootScope.$broadcast('savedItem');
				});
			}
		};
		return $scope.close = function() {
			return $uibModalInstance.close();
		};
	}
]);
