// Generated by CoffeeScript 1.10.0
'use strict';

/**
 * @ngdoc function
 * @name sgaAdminApp.controller:AchievementCtrl
 * @description
 * # AchievementCtrl
 * Controller of the sgaAdminApp
 */
angular.module('sgaAdminApp').controller('GamesProfileNewLeaderboardCtrl', [
	'$scope', '$stateParams', '$location', 'modalManager', 'LeaderboardsApi',
	function($scope, $stateParams, $location, modalManager, LeaderboardsApi) {
		$scope.itemId = $stateParams.itemId;
		$scope.item = {};

		$scope.create = function() {
			$scope.item.GameId = parseInt($scope.itemId);
			return LeaderboardsApi['leaderboard'].createFilter($scope.item).then(function() {
				$location.path('/games/' + $scope.itemId + '/leaderboards');
			});
		};
		$scope.back = function() {
			//go back to list of achievements for this game
			$location.path('/games/' + $scope.itemId + '/leaderboards');
		};
		return $scope.$on('savedItem', function(event, args) {
			return $scope.init();
		});
	}
]);
