// Generated by CoffeeScript 1.10.0
'use strict';

/**
  * @ngdoc function
  * @name sgaAdminApp.controller:GroupsCtrl
  * @description
  * # GroupsCtrl
  * Controller of the sgaAdminApp
 */
angular.module('sgaAdminApp').controller('GroupsCtrl', [
  '$scope', '$routeParams', '$location', 'modalManager', 'Api', function($scope, $routeParams, $location, modalManager, Api) {
    $scope.itemtype = $routeParams.itemtype;
    $scope.itemid = $routeParams.itemid;
    
    $scope.items = [];
    $scope.pagination = {
      perPage: 10,
      currentPage: 1
    };
    $scope.init = function() {
      return Api['groups'].list().then(function(res) {
        if (res.status === 200 && res.data != null) {
          $scope.items = res.data;
            //get the number of members for each groups
            $scope.allData = [];

              for (var i in $scope.items)
              {
                //loop through our items and pass through the index for us to ensure we set the number of members correctly
                (function(i){
                  Api['members'].list($scope.items[i].Id).then(function(res)
                  {
                    $scope.items[i].members = null;
                      $scope.items[i].members = res.data.length;
                  });
                })(i);
              }
          // if ($routeParams.itemid != null) {
          //   return $scope.items.forEach(function(i) {
          //     var a, b;
          //     a = '' + i[$scope.config.display.individualId];
          //     b = '' + $scope.itemid;
          //     if (a === b) {
          //       return $scope.select(i);
          //     }
          //   });
          // }
        }
      });
    };
    $scope.select = function(item) {
      return modalManager.open('edit', {
        itemtype: $scope.itemtype,
        item: item
      });
    };
    $scope["delete"] = function(item) {
      return modalManager.open('delete', {
        itemtype: $scope.itemtype,
        item: item
      });
    };
    $scope.create = function() {
      return modalManager.open('create', {
        itemtype: $scope.itemtype
      });
    };
    $scope.showMembers = function(item) {
      return modalManager.open('showMembers', {
        itemtype: $scope.itemtype,
        item: item
      });
    };
    $scope.showGroups = function(item) {
      return modalManager.open('showGroups', {
        itemtype: $scope.itemtype,
        item: item
      });
    };
    return $scope.$on('savedItem', function(event, args) {
      return $scope.init();
    });
  }
]).controller('EditModalCtrl', [
  '$scope', '$rootScope', '$uibModalInstance', 'Api', 'modalManager', 'modaldata', function($scope, $rootScope, $uibModalInstance, Api, modalManager, modaldata) {
    $scope.itemtype = modaldata.itemtype;
    $scope.config = modaldata.config;
    if (modaldata.item != null) {
      $scope.item = modaldata.item;
    } else if (modaldata.itemid != null) {
      $scope.item = {};
      Api[$scope.itemtype].get(modaldata.itemid).then(function(data) {
        if ((data != null ? data.data : void 0) != null) {
          return $scope.item = data.data;
        } else {
          return $uibModalInstance.close();
        }
      });
    } else {
      $uibModalInstance.close();
    }
    $scope.editables = $scope.config.editables.view;
    $scope.editables.forEach(function(e) {
      return e.original = $scope.item[e.key];
    });
    $scope.link = function(itemtype, id) {
      return modalManager.open('edit', {
        itemtype: itemtype,
        itemid: id
      });
    };
    $scope.save = function() {
      return Api[$scope.itemtype].update($scope.item.Id, $scope.item).then(function() {
        $uibModalInstance.close();
        return $rootScope.$broadcast('savedItem');
      });
    };
    return $scope.close = function() {
      $scope.editables.forEach(function(e) {
        return $scope.item[e.key] = e.original;
      });
      return $uibModalInstance.close();
    };
  }
]).controller('CreateModalCtrl', [
  '$scope', '$rootScope', '$uibModalInstance', 'Api', 'modaldata', function($scope, $rootScope, $uibModalInstance, Api, modaldata) {
    $scope.itemtype = modaldata.itemtype;
    $scope.config = modaldata.config;
    $scope.item = {};
    
    Object.keys($scope.config.defaultNew).forEach(function(k) {
      return $scope.item[k] = $scope.config.defaultNew[k];
    });
    $scope.editables = $scope.config.editables.create;
    $scope.save = function() {
        return Api[$scope.itemtype].create($scope.item).then(function() {
            $uibModalInstance.close();
            return $rootScope.$broadcast('savedItem');
        });
    };
    return $scope.close = function() {
      return $uibModalInstance.close();
    };
  }
]).controller('ConfirmDeleteModalCtrl', [
  '$scope', '$rootScope', '$uibModalInstance', 'Api', 'modaldata', function($scope, $rootScope, $uibModalInstance, Api, modaldata) {
    $scope.itemtype = modaldata.itemtype;
    $scope.config = modaldata.config;
    if (modaldata.item != null) {
      $scope.item = modaldata.item;
    } else if (modaldata.itemid != null) {
      $scope.item = {};
      Api[$scope.itemtype].get(modaldata.itemid).then(function(data) {
        return console.log(data);
      });
    }
    $scope["delete"] = function() {
      return Api[$scope.itemtype]["delete"]($scope.item.Id).then(function() {
        $uibModalInstance.close();
        return $rootScope.$broadcast('savedItem');
      });
    };
    return $scope.close = function() {
      return $uibModalInstance.close();
    };
  }
]).controller('showMembersModalCtrl', [
  '$scope', '$rootScope', '$uibModalInstance', 'Api', 'modalManager', 'modaldata', function($scope, $rootScope, $uibModalInstance, Api, modalManager, modaldata) {
    $scope.itemtype = modaldata.itemtype;
    $scope.config = modaldata.config;
    $scope.item = modaldata.item;

    {
        Api['members'].list($scope.item.Id).then(function(res) {
        if ((res != null ? res.status : void 0) === 200 && (res.data != null)) {
          $scope.items = res.data;
        }
       });
    }
    
    //our buttons
    $scope.remove = function(item){
        var friendship = "{ RequestorId: " + item.Id + ", AcceptorId: " + $scope.item.Id + ", Accepted: false }"
        Api['members'].update(friendship).then(function(res) {
            $uibModalInstance.close();
            return modalManager.open('showMembers', {
            itemtype: $scope.itemtype,
            item: $scope.item
            });
        });
    }; 
    $scope.close = function() {
      return $uibModalInstance.close();
    };
    return $scope.add = function(item) {
        $uibModalInstance.close();
      return modalManager.open('addMember', {
        itemtype: $scope.itemtype,
        item: item
      });
    };
    
  }
]).controller('addMemberModalCtrl', [
  '$scope', '$rootScope', '$uibModalInstance', 'Api', 'modalManager', 'modaldata', function($scope, $rootScope, $uibModalInstance, Api, modalManager, modaldata) {
    $scope.itemtype = modaldata.itemtype;
    $scope.config = modaldata.config;
    
    if (modaldata.item != null) {
      $scope.item = modaldata.item;
    } else if (modaldata.itemid != null) {
      Api[$scope.itemtype].get(modaldata.itemid).then(function(data) {
        if ((data != null ? data.data : void 0) != null) {
          return $scope.item = data.data;
        }
      });
    }
    //our buttons
    $scope.close = function(item) {
        $scope.config.members.ExistingPlayer.exists = true;
        return $uibModalInstance.close();
    };
    return $scope.add = function(item) {
        Api['users'].get($scope.txtBox)
        
        .then(function(res)
        {
            if (res.data[0]!=null)
            {
                //put the data backwards for testing as groups cannot request users join
                var friendship = "{ RequestorId: " + res.data[0].Id + ", AcceptorId: " + item.Id + ", AutoAccept: true }"
                Api['members'].create(friendship).then(function(res){
                $uibModalInstance.close();
                return modalManager.open('showMembers', {
                    itemtype: $scope.itemtype,
                    item: item
                });
            });
            }
            else
                $scope.config.members.ExistingPlayer.exists = false;
        });
    };
  }
]);
