// Generated by CoffeeScript 1.10.0
'use strict';

/**
  * @ngdoc function
  * @name sgaAdminApp.controller:HeaderCtrl
  * @description
  * # HeaderCtrl
  * Controller of the sgaAdminApp
 */
angular.module('sgaAdminApp').controller('HeaderCtrl', ['$scope', '$location', function($scope, $location) {}]);
