// Generated by CoffeeScript 1.10.0
'use strict';

/**
  * @ngdoc function
  * @name sgaAdminApp.controller:GroupsCtrl
  * @description
  * # GroupsCtrl
  * Controller of the sgaAdminApp
 */
angular.module('sgaAdminApp').controller('LeaderboardsFilterCtrl', [
  '$scope', '$routeParams', '$location', 'modalManager', 'LeaderboardsApi', function($scope, $routeParams, $location, modalManager, LeaderboardsApi) {
    $scope.itemtype = $routeParams.itemtype;
    $scope.itemId = $routeParams.itemId;
    
    $scope.gameFound = true;

    $scope.items = [];
    $scope.pagination = {
      perPage: 10,
      currentPage: 1
    };
    $scope.init = function() {
      return LeaderboardsApi['games'].listFilters($scope.itemId).then(function(res) {
        if (res.status === 200 && res.data != null) {
          $scope.items = res.data;
        }
      });
    };
    LeaderboardsApi['games'].get($scope.itemId).then(function(res){
        if (res.status === 200 && res.data != null)
        {
          $scope.gameFound = true;
        }
        else 
        {
          $scope.gameFound = false;
        }
      }).catch(function () {
        $scope.gameFound = false;
      });
    $scope.addFilter = function(item) {
      return modalManager.open('newFilter', {} );
    };
    return $scope.$on('savedItem', function(event, args) {
      return $scope.init();
    });
  }
]).controller('CreateFilterModalCtrl', [
  '$scope', '$rootScope', '$uibModalInstance', 'LeaderboardsApi', 'modaldata', function($scope, $rootScope, $uibModalInstance, LeaderboardsApi, modaldata) {
    $scope.itemtype = modaldata.itemtype;
    $scope.config = modaldata.config;
    $scope.item = {};
    
    $scope.save = function() {
        return LeaderboardsApi['games'].createFilter($scope.item).then(function() {
            $uibModalInstance.close();
            return $rootScope.$broadcast('savedItem');
        });
    };
    return $scope.close = function() {
      return $uibModalInstance.close();
    };
  }
]);
