// Generated by CoffeeScript 1.10.0
'use strict';

/**
 * @ngdoc function
 * @name sgaAdminApp.controller:GroupsCtrl
 * @description
 * # GroupsCtrl
 * Controller of the sgaAdminApp
 */
angular.module('sgaAdminApp').controller('ResourcesActorsManageCtrl', [
	'$scope', '$routeParams', '$location', 'modalManager', 'ResourcesApi',
	function($scope, $routeParams, $location, modalManager, ResourcesApi) {
		$scope.itemId = $routeParams.itemId;
		$scope.actorType = $routeParams.actorType;
		$scope.actorId = $routeParams.actorId;

		$scope.item = {};
		$scope.actorItems ={};

		$scope.gameFound = true;
		$scope.gameName = '';

		$scope.actorName;

		$scope.items = [];
		$scope.pagination = {
			perPage: 10,
			currentPage: 1
		};
		$scope.init = function() {
			ResourcesApi['games'].listPlayerResources($scope.actorId, $scope.itemId).then(function(res)
			{
				if (res.status === 200 && res.data != null){
					$scope.actorItems = res.data;
				}
			});
			return ResourcesApi['games'].listResources($scope.itemId).then(function(res) {
				if (res.status === 200 && res.data != null) {
					$scope.items = res.data;
				}
			});
		};
		ResourcesApi['games'].get($scope.itemId).then(function(res) {
			if (res.status === 200 && res.data != null) {
				$scope.gameFound = true;
				$scope.gameName = res.data.name;
			} else {
				$scope.gameFound = false;
			}
		}).catch(function() {
			$scope.gameFound = false;
		});
		ResourcesApi[$scope.actorType].get($scope.actorId).then(function(res) {
			if (res.status === 200 && res.data != null) {
				$scope.actorName = res.data.name;
			}
		});
		$scope.back = function() {
			//go back to resources games list
			$location.path("/resources/" + $scope.itemId);
		};
		$scope.setValue = function(item) {
			//extract the info we need to update the item
			var resourceItem = {};
			resourceItem.ActorId = $scope.actorId;
			resourceItem.GameId = item.gameId;
			resourceItem.Key = item.key;
			resourceItem.Quantity = item.Value;
			ResourcesApi['resources'].update(resourceItem).then(function(){
				$scope.init();
			});
		}
		return $scope.$on('savedItem', function(event, args) {
			return $scope.init();
		});
	}
]);
