// Generated by CoffeeScript 1.10.0
'use strict';

/**
 * @ngdoc function
 * @name sgaAdminApp.controller:GroupsCtrl
 * @description
 * # GroupsCtrl
 * Controller of the sgaAdminApp
 */
angular.module('sgaAdminApp').controller('ResourcesActorsManageCtrl', [
	'$scope', '$routeParams', '$location', 'modalManager', 'ResourcesApi',
	function($scope, $routeParams, $location, modalManager, ResourcesApi) {
		$scope.itemId = $routeParams.itemId;
		$scope.actorType = $routeParams.actorType;
		$scope.actorId = $routeParams.actorId;

		$scope.item = {};
		$scope.actorItems ={};

		$scope.gameFound = true;
		$scope.gameName = '';

		$scope.actorName;

		$scope.items = [];
		$scope.pagination = {
			perPage: 10,
			currentPage: 1
		};
		$scope.init = function() {
			if ($scope.itemId != "global")
			{
				ResourcesApi['games'].listActorResources($scope.actorId, $scope.itemId).then(function(res)
				{
					if (res.status === 200 && res.data != null){
						$scope.actorItems = res.data['response'];
					}
				});
				ResourcesApi['games'].listResources($scope.itemId).then(function(res) {
					if (res.status === 200 && res.data != null) {
						$scope.items = res.data['response'];
					}
				});

				ResourcesApi['games'].get($scope.itemId).then(function(res) {
					if (res.status === 200 && res.data != null) {
						$scope.gameFound = true;
						$scope.gameName = res.data['response'].name;
					} else {
						$scope.gameFound = false;
					}
				}).catch(function() {
					$scope.gameFound = false;
				});
				ResourcesApi[$scope.actorType].get($scope.actorId).then(function(res) {
					if (res.status === 200 && res.data != null) {
						$scope.actorName = res.data['response'].name;
					}
				});
			}
			else
			{
				ResourcesApi['games'].listActorGlobalResources().then(function(res)
				{
					if (res.status === 200 && res.data != null){
						$scope.actorItems = res.data['response'];
					}
				});
				ResourcesApi['games'].listGlobalResources().then(function(res) {
					if (res.status === 200 && res.data != null) {
						$scope.items = res.data['response'];
					}
				});	

				$scope.gameName = "Global";
				$scope.actorName = "";
				$scope.gameFound = true;
			}

		};
		
		$scope.back = function() {
			//go back to resources games list
			$location.path("/resources/" + $scope.itemId);
		};
		$scope.setValue = function(item) {
			//extract the info we need to update the item
			var resourceItem = {};
			resourceItem.ActorId = $scope.actorId;
			resourceItem.GameId = item.gameId;
			resourceItem.Key = item.key;
			resourceItem.Quantity = item.Value;
			ResourcesApi['resources'].update(resourceItem).then(function(){
				$scope.init();
			});
		}
		return $scope.$on('savedItem', function(event, args) {
			return $scope.init();
		});
	}
]);
