// Generated by CoffeeScript 1.10.0
'use strict';

/**
  * @ngdoc function
  * @name sgaAdminApp.controller:SidebarCtrl
  * @description
  * # SidebarCtrl
  * Controller of the sgaAdminApp
 */
angular.module('sgaAdminApp').controller('SidebarCtrl', [
  '$scope', '$location', 'listConfigs', function($scope, $location, listConfigs) {
    $scope.isActive = function(page) {
      return $location.path().indexOf("/list/" + page) !== -1;
    };
    return $scope.pages = listConfigs;
  }
]);
