// Generated by CoffeeScript 1.10.0
'use strict';

/**
 * @ngdoc function
 * @name sgaAdminApp.controller:UsersCtrl
 * @description
 * # UsersCtrl
 * Controller of the sgaAdminApp
 */
angular.module('sgaAdminApp').controller('UsersProfileCtrl', [
	'$scope', '$routeParams', '$location', 'modalManager', 'UsersApi',
	function($scope, $routeParams, $location, modalManager, UsersApi) {
		$scope.itemtype = $routeParams.itemtype;
		$scope.itemId = $routeParams.itemId;

		$scope.showFriends = false;
		$scope.showGroups = false;
		$scope.showInfo = false;

		$scope.userFound = true;

		$scope.userName = '';

		$scope.items = [];
		$scope.pendings = [];
		$scope.requests = [];

		$scope.pagination = {
			perPage: 10,
			currentPage: 1
		};
		$scope.init = function() {
			if ($scope.showFriends)
			{
				$scope.items = [];
				$scope.pendings = [];
				$scope.requests = [];
				UsersApi['friends'].list($scope.itemId).then(function(res) {
					if ((res != null ? res.status : void 0) === 200 && (res.data['response'].length > 0)) {
						$scope.items = res.data['response'];
					}
				});
				UsersApi['friendRequests'].listPending($scope.itemId).then(function(res) {
					if (res.status === 200 && res.data != null) {
						$scope.pendings = res.data['response'];
					}
				});
				UsersApi['friendRequests'].list($scope.itemId).then(function(res) {
					if (res != null && res.data != null) {
						$scope.requests = res.data['response'];
					}
				});
			}
			if ($scope.showGroups)
			{
				UsersApi['userGroups'].list($scope.itemId).then(function(res) {
				if (res.status === 200 && res.data != null) {
					$scope.items = res.data['response'];
				}
			});
			}
			UsersApi['users'].getById($scope.itemId).then(function(res) {
				if (res.status === 200 && res.data['response'].name != null) {
					$scope.userName = res.data['response'].name;
					$scope.userFound = true;
				} else {
					$scope.userFound = false;
				}
			}).catch(function() {
				$scope.userFound = false;
			});
		};
		$scope.userFriends = function() {
			$scope.showGroups = false;
			$scope.showInfo = false;
			$scope.showFriends = true;

			$scope.init();
			//$location.path('/users/' + $scope.itemId + '/friends');
		};
		$scope.userGroups = function() {
			$scope.showFriends = false;
			$scope.showInfo = false;
			$scope.showGroups = true;

			$scope.init();
			//$location.path('/users/' + $scope.itemId + '/groups');
		};
		$scope.userInfo = function(){
			$scope.showFriends = false;
			$scope.showGroups = false;
			$scope.showInfo = true;

			$scope.init();
		};
		$scope.closeTable = function(){
			$scope.showGroups = false;
			$scope.showFriends = false;
			$scope.showInfo = false;

			$scope.init();
		};
		$scope.back = function() {
			//go back to users list
			$location.path("/users");
		};
		return $scope.$on('savedItem', function(event, args) {
			return $scope.init();
		});

	}
]);