// Generated by CoffeeScript 1.10.0
'use strict';

/**
 * @ngdoc function
 * @name sgaAdminApp.controller:UsersCtrl
 * @description
 * # UsersCtrl
 * Controller of the sgaAdminApp
 */
angular.module('sgaAdminApp').controller('UsersGroupsCtrl', [
	'$scope', '$routeParams', '$location', 'modalManager', 'UsersApi',
	function($scope, $routeParams, $location, modalManager, UsersApi) {
		$scope.itemtype = $routeParams.itemtype;
		$scope.itemId = $routeParams.itemId;

		$scope.userName = '';
		$scope.userFound = true;

		$scope.items = [];
		$scope.pagination = {
			perPage: 10,
			currentPage: 1
		};
		$scope.init = function() {
			UsersApi['userGroups'].list($scope.itemId).then(function(res) {
				if (res.status === 200 && res.data != null) {
					$scope.items = res.data['response'];
				}
			});
			UsersApi['users'].getById($scope.itemId).then(function(res) {
				if (res.status === 200 && res.data != null) {
					$scope.userName = res.data['response'].name;
				} else {
					$scope.userFound = false;
				}
			}).catch(function() {
				$scope.userFound = false;
			});
		};

		$scope.add = function(item) {
			return modalManager.open('addGroup', {
				itemtype: $scope.itemtype,
				itemId: $scope.itemId,
				item: item
			});
		};
		$scope.remove = function(item) {
			var friendship = "{ RequestorId: " + $scope.itemId + ", AcceptorId: " + item.id + ", Accepted: false }"
			UsersApi['userGroups'].update(friendship).then(function(res) {
				$scope.init();
			});
		}
		$scope.back = function() {
			//go back to user profile
			$location.path("/users/" + $scope.itemId);
		};
		return $scope.$on('savedItem', function(event, args) {
			return $scope.init();
		});
	}
]).controller('showGroupsModalCtrl', [
	'$scope', '$rootScope', '$uibModalInstance', 'UsersApi', 'modalManager', 'modaldata',
	function($scope, $rootScope, $uibModalInstance, UsersApi, modalManager, modaldata) {
		$scope.itemtype = modaldata.itemtype;
		$scope.config = modaldata.config;
		$scope.item = modaldata.item;

		UsersApi['userGroups'].list($scope.item.id).then(function(res) {
			if ((res != null ? res.status : void 0) === 200 && (res.data != null)) {
				$scope.items = res.data['response'];
			}
		});

		//our buttons
		$scope.close = function() {
			return $uibModalInstance.close();
		};

	}
]);