// Generated by CoffeeScript 1.10.0
'use strict';

/**
  * @ngdoc service
  * @name sgaAdminApp.Api
  * @description
  * # Api
  * Service in the sgaAdminApp.
 */
// angular.module('sgaAdminApp').service('Api', [
//   '$http', 'config', function($http, config) {
    
//   }
// ]);
