// Generated by CoffeeScript 1.10.0
'use strict';

/**
  * @ngdoc service
  * @name sgaAdminApp.Api
  * @description
  * # Api
  * Service in the sgaAdminApp.
 */
angular.module('sgaAdminApp').service('Api', [
  '$http', 'config', function($http, config) {
    return {
      'users': {
        list: function() {
          return $http.get(config.api.baseurl + '/players');
        },
        get: function(id) {
          return $http.get(config.api.baseurl + ("/players/" + id));
        },
        create: function(item) {
          return $http.post(config.api.baseurl + '/players', item);
        },
        update: function(id, item) {
          return $http.put(config.api.baseurl + ("/players/" + id), item);
        },
        "delete": function(id) {
          return $http["delete"](config.api.baseurl + ("/players/" + id));
        }
      },
      'groups': {
        list: function() {
          return $http.get(config.api.baseurl + '/groups');
        },
        get: function(id) {
          return $http.get(config.api.baseurl + ("/groups/actor/" + id));
        },
        create: function(item) {
          return $http.post(config.api.baseurl + '/groups', item);
        },
        update: function(id, item) {
          return $http.put(config.api.baseurl + ("/groups/" + id), item);
        },
        "delete": function(id) {
          return $http["delete"](config.api.baseurl + ("/groups/" + id));
        }
      },
      'achievements': {
          list: function(){
              return $http.get(config.api.baseurl + '/achievements');
          },
          create: function(item) {
            return $http.post(config.api.baseurl + '/achievements', item);  
          }
      },
      'games':{
          list: function(){
              return $http.get(config.api.baseurl + '/games')
          },
          create: function(item) {
            return $http.post(config.api.baseurl + '/games', item);  
          }
      },
      'friends': {
        list: function() {
          return $http.get(config.api.baseurl + "/players");
        },
        // list: function(item) {
        //   return $http.get(config.api.baseurl + "/players/" + item.id);  
        // },
        get: function(id) {
          return $http.get(config.api.baseurl + ("/players/" + id));
        },
        update: function(id, item) {
          return $http.put(config.api.baseurl + ("/players/" + id), item);
        },
        "delete": function(id) {
          return $http["delete"](config.api.baseurl + ("/players/" + id));
        }
      },
      'playerGroups': {
        list: function() {
          return $http.get(config.api.baseurl + '/players');
        },
        get: function(id) {
          return $http.get(config.api.baseurl + ("/alliances/" + id));
        },
        update: function(id, item) {
          return $http.put(config.api.baseurl + ("/alliances/" + id), item);
        },
        "delete": function(id) {
          return $http["delete"](config.api.baseurl + ("/alliances/" + id));
        }
      },
      'members': {
        list: function() {
          return $http.get(config.api.baseurl + '/players');
        },
        get: function(id) {
          return $http.get(config.api.baseurl + ("/alliances/" + id));
        },
        update: function(id, item) {
          return $http.put(config.api.baseurl + ("/alliances/" + id), item);
        },
        "delete": function(id) {
          return $http["delete"](config.api.baseurl + ("/alliances/" + id));
        }
      }
    };
  }
]);
