// Generated by CoffeeScript 1.10.0
'use strict';

/**
  * @ngdoc service
  * @name sgaAdminApp.Api
  * @description
  * # Api
  * Service in the sgaAdminApp.
 */
angular.module('sgaAdminApp').service('GamesApi', [
  '$http', 'config', function($http, config) {
    return {
      'achievements': {
          list: function(id){
              return $http.get(config.api.baseurl + '/groupachievement?gameId=' + id);
          },
          create: function(item) {
            return $http.post(config.api.baseurl + '/groupachievement', item);  
          },
          "delete": function(id){
              return $http["delete"](config.api.baseurl + '/groupachievement?Id=' + id);
          }
      },
      'games':{
          list: function(){
              return $http.get(config.api.baseurl + '/game/all')
          },
          get: function(id) {
            return $http.post(config.api.baseurl + '/game?Id=' + id);  
          },
          create: function(item) {
            return $http.post(config.api.baseurl + '/game', item);  
          },
          "delete": function(id){
              return $http["delete"](config.api.baseurl + '/game?Id=' + id);
          }
      }
    };
  }
]);
