// Generated by CoffeeScript 1.10.0
'use strict';

/**
  * @ngdoc service
  * @name sgaAdminApp.listConfigs
  * @description
  * # listConfigs
  * Service in the sgaAdminApp.
 */
angular.module('sgaAdminApp').service('listConfigs', [
  '$http', 'config', function($http, config) {
    return {
      'users': {
        enabled: {
          create: true,
          edit: true,
          "delete": true
        },
        display: {
          listed: true,
          title: 'Users',
          single: 'user',
          plural: 'users',
          individualTitle: function(item) {
            return item.Name;
          },
          individualId: 'Id',
          icon: 'fa-users'
        },
        columns: [
          {
            title: 'ID',
            key: 'Id' 
          },
          {
            title: 'Name',
            key: 'Name'
          }
        ],
        editables: {
          view: [
            {
              display: 'ID',
              key: 'Id',
              type: 'text',
              viewonly: true
            }, {
              display: 'Name',
              key: 'Name',
              type: 'text'
            }, {
              display: 'Email',
              key: 'email',
              type: 'email'
            }, {
              display: 'Is Enabled?',
              key: 'isEnabled',
              type: 'checkbox'
            }, {
              display: 'Type',
              key: 'type',
              type: 'text',
              viewonly: true
            }, {
              display: 'UpdatedDate',
              key: 'updatedDate',
              type: 'text',
              viewonly: true
            }, {
              display: 'CreatedDate',
              key: 'createdDate',
              type: 'text',
              viewonly: true
            }
          ],
          create: [
            {
              key: 'Username',
              type: 'text'
            }, {
              key: 'Password',
              type: 'password'
            }, {
              key: 'Email',
              type: 'email'
            }
          ]
        },
        defaultNew: {
          'Username': '',
          'Password': '',
          'Email': '',
          'ActivationCode': '00000000-0000-0000-0000-000000000000',
          'IsEnabled': false,
          'Type': 0,
          'LastLoginIp': null
        },
        friends: {
          enabled: {
            create: true,
            edit: true,
            "delete": true
          },
          display: {
            listed: false,
            title: 'Friends',
            single: 'friend',
            plural: 'friends',
            individualTitle: function(item) {
              return item.username;
            },
            individualId: 'Id',
            icon: 'fa-users'
          },
          ExistingPlayer: {
            exists: true
          },
          columns: [
            {
              title: 'Username',
              key: 'username'
            }, {
              title: 'Date Added',
              key: 'createdDate'
            }
          ]
        },
        playerGroups: {
          enabled: {
            create: true,
            edit: true,
            "delete": true
          },
          display: {
            listed: false,
            title: 'Friends',
            single: 'friend',
            plural: 'friends',
            individualTitle: function(item) {
              return item.username;
            },
            individualId: 'Id',
            icon: 'fa-users'
          },
          ExistingGroup: {
            exists: true
          },
          columns: [
            {
              title: 'Username',
              key: 'username'
            }, {
              title: 'Date Joined',
              key: 'createdDate'
            }
          ]
        }
      },
      'groups': {
        enabled: {
          create: true,
          edit: true,
          "delete": true
        },
        display: {
          listed: true,
          title: 'Groups',
          single: 'group',
          plural: 'groups',
          individualTitle: function(item) {
            return item.Name;
          },
          individualId: 'Id',
          icon: 'fa-users'
        },
        columns: [
          {
            title: 'Name',
            key: 'Name'
          }, {
            title: 'Members',
            key: 'members'
          }, {
            title: 'Date Created',
            key: 'createdDate'
          }
        ],
        editables: {
          view: [
            {
              display: 'Description',
              key: 'description',
              type: 'text'
            }, {
              display: 'Groups',
              type: 'link',
              itemtype: 'groups',
              val: function(item) {
                return item.groups[0].name;
              },
              Id: function(item) {
                return item.groups[0].Id;
              }
            }
          ],
          create: [
            {
              display: 'Description',
              key: 'description',
              type: 'text'
            }, {
              display: 'Group',
              key: 'group',
              type: 'dropdown',
              values: [
                {
                  Id: '1',
                  name: 'Group 1'
                }, {
                  Id: '2',
                  name: 'Group 2'
                }
              ]
            }
          ]
        },
        members: {
          enabled: {
            create: true,
            edit: true,
            "delete": true
          },
          display: {
            listed: false,
            title: 'Members',
            single: 'member',
            plural: 'members',
            individualTitle: function(item) {
              return item.Name;
            },
            individualId: 'Id',
            icon: 'fa-users'
          },
          ExistingPlayer: {
            exists: true
          },
          columns: [
            {
              title: 'Player Name',
              key: 'Name'
            // }, {
            //   title: 'Acceptor ID',
            //   key: 'AcceptorId'
            // }, {
            //     title: 'Accepted',
            //     key: 'Accepted'
            }
          ]
        }
      },
      'achievements': {
        enabled: {
          create: true,
          edit: true,
          "delete": true
        },
        display: {
          listed: true,
          title: 'Achievements',
          single: 'achievement',
          plural: 'achievements',
          individualTitle: function(item) {
            return item.Name;
          },
          individualId: 'Id',
          icon: 'fa-users'
        },
        columns: [
          {
            title: 'Name',
            key: 'name'
          }, {
            key: 'Reward',
            type: 'reward'
          }, {
            title: 'Date Created',
            key: 'createdDate'
          }
        ],
        editables: {
          view: [
            {
              display: 'Name',
              key: 'name',
              type: 'text'
            }, {
              display: 'UpdatedDate',
              key: 'updatedDate',
              type: 'text',
              viewonly: true
            }, {
              display: 'CreatedDate',
              key: 'createdDate',
              type: 'text',
              viewonly: true
            }
          ],
          create: [
            {
              key: 'Name',
              type: 'name'
            }
          ]
        },
        defaultNew: {
          'Name': '',
        }
      },
       'games': {
        enabled: {
          create: true,
          edit: true,
          "delete": true
        },
        display: {
          listed: true,
          title: 'Games',
          single: 'game',
          plural: 'games',
          individualTitle: function(item) {
            return item.Name;
          },
          individualId: 'Id',
          icon: 'fa-users'
        },
        columns: [
          {
            title: 'Name',
            key: 'name'
          }, {
            title: 'Date Created',
            key: 'createdDate'
          }
        ],
        editables: {
          view: [
            {
              display: 'Name',
              key: 'name',
              type: 'text'
            }, {
              display: 'UpdatedDate',
              key: 'updatedDate',
              type: 'text',
              viewonly: true
            }, {
              display: 'CreatedDate',
              key: 'createdDate',
              type: 'text',
              viewonly: true
            }
          ],
          create: [
            {
              key: 'Name',
              type: 'name'
            }
          ]
        },
        defaultNew: {
          'Name': '',
        }
      }
    };
  }
]);
