
// Generated by CoffeeScript 1.10.0
'use strict';

/**
 * @ngdoc service
 * @name sgaAdminApp.Api
 * @description
 * # Api
 * Service in the sgaAdminApp.
 */
angular.module('sgaAdminApp').service('RolesApi', [
	'$http', 'config',
	function($http, config) {
		return {
			'roles': {
				list: function() {
					return $http.get(config.api.baseurl + '/role/list');
				},
				create: function(item) {
					return $http.post(config.api.baseurl + '/role', item);
				},
				"delete": function(id) {
					return $http["delete"](config.api.baseurl + ("/user/" + id));
				}
			},
			'claims': {
				list: function(id){
					return $http.get(config.api.baseurl + '/RoleClaim/role/' + id);
				},
				create: function(item){
					return $http.post(config.api.baseurl + '/roleclaim', item);
				},
				"delete": function(roleId, claimId){
					return $http.get(config.api.baseurl + '/role/' + roleId + '/claim/' + claimId);
				}
			}
		};
	}
]);
