
// Generated by CoffeeScript 1.10.0
'use strict';

/**
 * @ngdoc service
 * @name sgaAdminApp.Api
 * @description
 * # Api
 * Service in the sgaAdminApp.
 */
angular.module('sgaAdminApp').service('RolesApi', [
	'$http', 'config',
	function($http, config) {
		return {
			'roles': {
				list: function() {
					return $http.get(config.api.baseurl + '/role/list');
				},
				listScope: function(scope) {
					return $http.get(config.api.baseurl + '/role/scope/' + scope);
				},
				getActorRole: function(actorId, entityId, scopeName) {
					return $http.get(config.api.baseurl + '/ActorRole/actor/' + actorId + '/entity/' + entityId + '/claimscope/' + scopeName);
				},
				getActorsForRole: function(roleId, entityId) {
					return $http.get(config.api.baseurl + '/ActorRole/role/' + roleId + '/entity/' + entityId)
				},
				create: function(item) {
					return $http.post(config.api.baseurl + '/role', item);
				},
				"delete": function(id) {
					return $http["delete"](config.api.baseurl + ("/user/" + id));
				}
			},
			'claims': {
				list: function(id){
					return $http.get(config.api.baseurl + '/RoleClaim/role/' + id);
				},
				create: function(item){
					return $http.post(config.api.baseurl + '/roleclaim', item);
				},
				"delete": function(roleId, claimId){
					return $http.get(config.api.baseurl + '/role/' + roleId + '/claim/' + claimId);
				}
			},
			'actorClaim': {
				list: function(id){
					return $http.get(config.api.baseurl + '/ActorClaim/actor/' + id)
				},
			},
			'updateRoles': {
				CreateActorRole: function(item){
					return $http.post(config.api.baseurl + '/actorRole', item)
				},
				"delete": function(actorId, entityId, roleId){
					return $http["delete"](config.api.baseurl + '/ActorRole/actor/' + actorId + '/entity/' + entityId + '/role/' + roleId)
				}
			}
		};
	}
]);
