// Generated by CoffeeScript 1.10.0
'use strict';

/**
 * @ngdoc service
 * @name sgaAdminApp.Api
 * @description
 * # Api
 * Service in the sgaAdminApp.
 */
angular.module('sgaAdminApp').service('SkillsApi', [
	'$http', 'config',
	function($http, config) {
		return {
			'skills': {
				list: function() {
					return $http.get(config.api.baseurl + '/skills/list')
				},
				listSkills: function(id) {
					return $http.get(config.api.baseurl + '/skills/game/' + id + '/list');
				},
				get: function(id) {
					return $http.get(config.api.baseurl + '/skills/game/' + id);
				},
				createSkill: function(item) {
					return $http.post(config.api.baseurl + '/skills/create', item);
				},
				"delete": function(id) {
					return $http["delete"](config.api.baseurl + '/skills/' + id);
				}
			},
			'games': {
				list: function() {
					return $http.get(config.api.baseurl + '/game/list')
				},
				get: function(id) {
					return $http.get(config.api.baseurl + '/game/findbyid/' + id);
				}
			},
			'user': {
				get: function(username) {
					return $http.get(config.api.baseurl + '/user/find/' + username);
				}
			}
		};
	}
]);
