// Generated by CoffeeScript 1.10.0
'use strict';

/**
 * @ngdoc service
 * @name sgaAdminApp.Api
 * @description
 * # Api
 * Service in the sgaAdminApp.
 */
angular.module('sgaAdminApp').service('LeaderboardsApi', [
	'$http', 'config',
	function($http, config) {
		return {
			'games': {
				list: function() {
					return $http.get(config.api.baseurl + '/game/list')
				},
				listFilters: function(id) {
					return $http.get(config.api.baseurl + 'NEEDS API CALL' + id)
				},
				get: function(id) {
					return $http.get(config.api.baseurl + '/game/findbyid/' + id);
				},
				create: function(item) {
					return $http.post(config.api.baseurl + '/game', item);
				},
				"delete": function(id) {
					return $http["delete"](config.api.baseurl + '/game/' + id);
				}
			},
			'user': {
				get: function(username) {
					return $http.get(config.api.baseurl + '/user/find/' + username);
				}
			},
			'leaderboard': {
				list: function(id) {
					return $http.get(config.api.baseurl + '/leaderboards/game/' + id + '/list');
				},
				getGlobal: function(){
					return $http.get(config.api.baseurl + '/leaderboards/global/list');
				},
				createFilter: function(item) {
					return $http.post(config.api.baseurl + '/leaderboards/create', item);
				},
				getByToken: function(gameId, token)
				{
					return $http.get(config.api.baseurl + '/leaderboards/' + token + "/" + gameId);
				},
				getGlobalConfig: function(token){
					return $http.get(config.api.baseurl + '/leaderboards/' + token + '/global');
				},
				getLeaderboard: function(item) {
					return $http.post(config.api.baseurl + '/leaderboards/standings', item);
				},
				updateFilter: function(item) {
					return $http.put(config.api.baseurl + '/leaderboards/update', item);
				},
				"delete": function(token, gameId) {
					return $http["delete"](config.api.baseurl + '/leaderboards/' + token + '/' + gameId);
				},
				"deleteGlobal": function (token){
					return $http["delete"](config.api.baseurl + '/leaderboards/' + token + '/global')
				}
			}
		};
	}
]);
