// Generated by CoffeeScript 1.10.0
'use strict';

/**
 * @ngdoc service
 * @name sgaAdminApp.Api
 * @description
 * # Api
 * Service in the sgaAdminApp.
 */
angular.module('sgaAdminApp').service('SourcesApi', [
	'$http', 'config',
	function($http, config) {
		return {
			'sources': {
				list: function() {
					return $http.get(config.api.baseurl + '/accountSource/list');
				},
				get: function(id) {
					return $http.get(config.api.baseurl + '/accountSource/findbyid/' + id);
				},
				create: function(item) {
					return $http.post(config.api.baseurl + '/accountSource', item);
				},
				update: function(item) {
					return $http.put(config.api.baseurl + '/accountSource', item);
				},
				"delete": function(id) {
					return $http["delete"](config.api.baseurl + '/accountSource/' + id);
				}
			}
		};
	}
]);
