// Generated by CoffeeScript 1.10.0
'use strict';

/**
  * @ngdoc service
  * @name sgaAdminApp.User
  * @description
  * # User
  * Service in the sgaAdminApp.
 */
angular.module('sgaAdminApp').factory('User', [
  '$http', 'config', function($http, config) {
    return {
      login: function(params) {
        return $http.get(config.api.baseurl + "/account?name=" + params.username + "&password=" + params.password);
      }
    };
  }
]);
