// Generated by CoffeeScript 1.10.0
'use strict';

/**
 * @ngdoc function
 * @name sgaAdminApp.controller:GroupsCtrl
 * @description
 * # GroupsCtrl
 * Controller of the sgaAdminApp
 */
angular.module('sgaAdminApp').controller('GroupsCtrl', [
	'$scope', '$stateParams', '$location', 'permissionService', 'modalManager', 'GroupsApi',
	function($scope, $stateParams, $location, permissionService, modalManager, GroupsApi) {
		$scope.itemtype = $stateParams.itemtype;
		$scope.itemid = $stateParams.itemid;

		$scope.permissionService = permissionService;

		$scope.hasGetListPermission;
		$scope.hasCreatePermission;

		$scope.items = [];
		$scope.pagination = {
			perPage: 10,
			currentPage: 1
		};
		$scope.init = function() {
			return GroupsApi['groups'].list().then(function(res) {
				// our permissions
				$scope.hasCreatePermission = true; //permissionService.hasAccessToClaim('Create-Group',-1);
				$scope.hasGetListPermission = true;

				if (res.status === 200 && res.data != null) {
					$scope.items = res.data['response'];
					//get the number of members for each groups
					$scope.allData = [];
				}
			}).catch(function(res){
				console.log(res.statusText);
			});
		};
		$scope.select = function(item) {
			return modalManager.open('editGroup', {
				itemtype: 'groups',
				item: item
			});
		};

		$scope.showProfile = function(item){
			$location.path('/groups/' + item.id);
		}
		$scope.create = function() {
			return modalManager.open('createGroup', {
				itemtype: 'groups'
			});
		};
		$scope.showMembers = function(item) {
			$location.path('/groups/' + item.id + '/members')
		};
		$scope.back = function() {
			//go back to main menu
			$location.path("/");
		};
		return $scope.$on('savedItem', function(event, args) {
			return $scope.init();
		});
	}
]).controller('CreateGroupModalCtrl', [
	'$scope', '$rootScope', '$uibModalInstance', 'GroupsApi', 'modaldata',
	function($scope, $rootScope, $uibModalInstance, GroupsApi, modaldata) {
		$scope.itemtype = modaldata.itemtype;
		$scope.config = modaldata.config;
		$scope.item = {};

		$scope.save = function() {
			return GroupsApi[$scope.itemtype].create($scope.item).then(function() {
				$uibModalInstance.close();
				return $rootScope.$broadcast('savedItem');
			});
		};
		return $scope.close = function() {
			$rootScope.$broadcast('savedItem');
			return $uibModalInstance.close();
		};
	}
]);
