// Generated by CoffeeScript 1.10.0
'use strict';

/**
 * @ngdoc function
 * @name sgaAdminApp.controller:GroupsCtrl
 * @description
 * # GroupsCtrl
 * Controller of the sgaAdminApp
 */
angular.module('sgaAdminApp').controller('GamesProfileResourcesCtrl', [
	'$scope', '$stateParams', '$location', 'modalManager', 'ResourcesApi', 'GroupsApi', 'UsersApi',
	function($scope, $stateParams, $location, modalManager, ResourcesApi, GroupsApi, UsersApi) {
		$scope.itemtype = $stateParams.itemtype;
		$scope.itemId = $stateParams.itemId;

		$scope.CreateNew = false;
		$scope.gameFound = true;
		$scope.gameName = '';

		$scope.items = [];
		$scope.pagination = {
			perPage: 20,
			currentPage: 1
		};
    $scope.init = function()
    {
      GroupsApi['groups'].list().then(function(res){
        if (res.status === 200 && res.data['response'] != null)
        {
          $scope.groups = res.data['response'];
        }
      });
      UsersApi['users'].list().then(function(res){
        if (res.status === 200 && res.data['response'] != null)
        {
          $scope.users = res.data['response'];
        }
      });
    }

    $scope.loadActorData = function(actor)
    {
      ResourcesApi['games'].listActorResources(actor.id, $scope.itemId).then(function(res){
				if (res.status === 200 && res.data['response'] != null)
				{
					$scope.items = res.data['response'];
					for (var i=0; i<$scope.items.length; i++)
					{
						$scope.items[i].index = i;
					}
				}
			});
    }

    $scope.addResource = function(item) {
      var resource = {};
      resource.key = item.key;
      resource.quantity = item.addAmount;
      resource.gameId = item.gameId;
      resource.actorId = item.actorId;

      ResourcesApi['resources'].update(resource).then(function(res) {
        if (res.status === 200 && res.data['response'].actorId != null)
        {
          item.addAmount = 0;
          item.quantity = res.data['response'].quantity;
        }
      });
    }

		$scope.addNew = function() {
			$scope.CreateNew = !$scope.CreateNew;
    }

    $scope.save = function(form) {
      form.gameId = $scope.itemId;
      // Get the actor id
      if (form.actorType == "user")
      {
        UsersApi['users'].get(form.actorName).then(function(res) {
					if (res.status === 200 && res.data['response'][0].id != null)
					{
						$scope.saveNewData(form, res.data['response'][0].id);
					}
					else
					{
						console.log("Unable to get actor with name: " + form.actorName);
					}
				}).catch(function() {
					console.log("Unable to get actor with name: " + form.actorName);
				});
      }
      else
      {
        GroupsApi['groups'].get(form.actorName).then(function(res) {
					if (res.status === 200 && res.data['response'][0].id != null)
					{
						$scope.saveNewData(form, res.data['response'][0].id);
					}
					else
					{
						console.log("Unable to get actor with name: " + form.actorName);
					}
				}).catch(function() {
					console.log("Unable to get actor with name: " + form.actorName);
				});
      }
    }

    $scope.saveNewData = function(data, actorId)
		{
      var resource = {};
      resource.gameId = data.gameId;
      resource.key = data.key;
      resource.actorId = actorId;
      resource.quantity = data.quantity;

      ResourcesApi['games'].createResource(resource).then(function() {
        $scope.CreateNew = false;
        $scope.items = [];
      });
		}

		$scope.back = function() {
			//go back to resources games list
			$location.path("/resources/" + $scope.itemId);
		};
		return $scope.$on('savedItem', function(event, args) {
			return $scope.init();
    });
	}
]);
