// Generated by CoffeeScript 1.10.0
'use strict';

/**
 * @ngdoc function
 * @name sgaAdminApp.controller:GroupsCtrl
 * @description
 * # GroupsCtrl
 * Controller of the sgaAdminApp
 */
angular.module('sgaAdminApp').controller('GamesProfileResourcesCtrl', [
	'$scope', '$stateParams', '$location', 'modalManager', 'ResourcesApi',
	function($scope, $stateParams, $location, modalManager, ResourcesApi) {
		$scope.itemtype = $stateParams.itemtype;
		$scope.itemId = $stateParams.itemId;

		$scope.gameFound = true;
		$scope.gameName = '';

		$scope.items = [];
		$scope.pagination = {
			perPage: 10,
			currentPage: 1
		};
		$scope.init = function() {
			if ($scope.itemId != "global")
			{
				ResourcesApi['games'].listResources($scope.itemId).then(function(res) {
					if (res.status === 200 && res.data != null) {
						$scope.items = res.data['response'];
					}
				});
				ResourcesApi['games'].get($scope.itemId).then(function(res) {
				if (res.status === 200 && res.data != null) {
					$scope.gameFound = true;
					$scope.gameName = res.data['response'].name;
				} else {
					$scope.gameFound = false;
				}
				}).catch(function() {
					$scope.gameFound = false;
				});
			}
			else
			{
				ResourcesApi['games'].listGlobalResources().then(function(res){
					if (res.status === 200 && res.data != null){
						$scope.item = res.data['response'];
					}
				});

				$scope.gameName = "Global";
				$scope.gameFound = true;
			}
		};
		
		$scope.addNew = function() {
			return modalManager.open('createResource', {
				itemId: $scope.itemId
			});
		}
		$scope.back = function() {
			//go back to resources games list
			$location.path("/resources/" + $scope.itemId);
		};
		return $scope.$on('savedItem', function(event, args) {
			return $scope.init();
		});
	}
])